CREATE TABLE [dbo].[Comments]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionID] INT FOREIGN KEY REFERENCES Transactions(ID) NULL, 
    [EventID] INT FOREIGN KEY REFERENCES Events(ID) NULL,
    [EntryDate] DATETIME NOT NULL,
    [CommentText] NVARCHAR(250) NOT NULL, 
)
